image_skip_batch_num: 7
image_num: 40
test_with_optimization: true
do_ba_two_frames: true
do_ba_backend: false #not effective
pnp_method: "epnp"
# pnp_method: "dls"
min_depth: 0.2
max_depth: 20.0
verbose: false
pause_after_optimization: true